-- Daily Planner: Supabase schema + Row Level Security
-- Run this entire script in Supabase SQL Editor.
-- IMPORTANT: create your first user in Authentication > Users.
-- Then set its password to the initial password you choose (e.g. hunter99).
-- Never store that password in this file or in GitHub.

create table if not exists public.daily_entries (
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  checks jsonb not null default '{}'::jsonb,
  review jsonb not null default '{"win":"","block":"","next":""}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, entry_date)
);

create table if not exists public.learning_topics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  session1_done boolean not null default false,
  session2_done boolean not null default false,
  position integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.daily_entries enable row level security;
alter table public.learning_topics enable row level security;

drop policy if exists "users read own daily entries" on public.daily_entries;
create policy "users read own daily entries"
on public.daily_entries for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users insert own daily entries" on public.daily_entries;
create policy "users insert own daily entries"
on public.daily_entries for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users update own daily entries" on public.daily_entries;
create policy "users update own daily entries"
on public.daily_entries for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users delete own daily entries" on public.daily_entries;
create policy "users delete own daily entries"
on public.daily_entries for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users read own topics" on public.learning_topics;
create policy "users read own topics"
on public.learning_topics for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users insert own topics" on public.learning_topics;
create policy "users insert own topics"
on public.learning_topics for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users update own topics" on public.learning_topics;
create policy "users update own topics"
on public.learning_topics for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users delete own topics" on public.learning_topics;
create policy "users delete own topics"
on public.learning_topics for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists daily_entries_user_date_idx
on public.daily_entries(user_id, entry_date);

create index if not exists learning_topics_user_position_idx
on public.learning_topics(user_id, position);

-- Keep updated_at current when rows change.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists daily_entries_updated_at on public.daily_entries;
create trigger daily_entries_updated_at
before update on public.daily_entries
for each row execute function public.set_updated_at();

drop trigger if exists learning_topics_updated_at on public.learning_topics;
create trigger learning_topics_updated_at
before update on public.learning_topics
for each row execute function public.set_updated_at();
